### ISSUE TITLE
Group component re-initializes @groups, which is never actually used

### ISSUE THREAD

**Issue by ryedin** [noflo/noflo-core#15]
see: https://github.com/noflo/noflo-core/blob/master/components/Group.coffee#L41

The `@groups` member is never actually used in this component. Should this be re-initializing `@newGroups` instead?

**Comment by bergie** [comment]
We should remove the `core/Groups` component, since noflo-groups has plenty of group handling components.

**Comment by bergie** [comment]
Removed in 0.4.x
